def language_dict():
    return [{'label': 'Afrikaans', 'value': 'af'},
 {'label': 'Amharic', 'value': 'am'},
 {'label': 'Aragonese', 'value': 'an'},
 {'label': 'Arabic', 'value': 'ar'},
 {'label': 'Assamese', 'value': 'as'},
 {'label': 'Azerbaijani', 'value': 'az'},
 {'label': 'Belarusian', 'value': 'be'},
 {'label': 'Bulgarian', 'value': 'bg'},
 {'label': 'Bengali', 'value': 'bn'},
 {'label': 'Breton', 'value': 'br'},
 {'label': 'Bosnian', 'value': 'bs'},
 {'label': 'Catalan; Valencian', 'value': 'ca'},
 {'label': 'Czech', 'value': 'cs'},
 {'label': 'Welsh', 'value': 'cy'},
 {'label': 'Danish', 'value': 'da'},
 {'label': 'German', 'value': 'de'},
 {'label': 'Dzongkha', 'value': 'dz'},
 {'label': 'Greek', 'value': 'el'},
 {'label': 'English', 'value': 'en'},
 {'label': 'Esperanto', 'value': 'eo'},
 {'label': 'Spanish; Castilian', 'value': 'es'},
 {'label': 'Estonian', 'value': 'et'},
 {'label': 'Basque', 'value': 'eu'},
 {'label': 'Persian', 'value': 'fa'},
 {'label': 'Finnish', 'value': 'fi'},
 {'label': 'Faroese', 'value': 'fo'},
 {'label': 'French', 'value': 'fr'},
 {'label': 'Irish', 'value': 'ga'},
 {'label': 'Galician', 'value': 'gl'},
 {'label': 'Gujarati', 'value': 'gu'},
 {'label': 'Hebrew', 'value': 'he'},
 {'label': 'Hindi', 'value': 'hi'},
 {'label': 'Croatian', 'value': 'hr'},
 {'label': 'Haitian; Haitian Creole', 'value': 'ht'},
 {'label': 'Hungarian', 'value': 'hu'},
 {'label': 'Armenian', 'value': 'hy'},
 {'label': 'Indonesian', 'value': 'id'},
 {'label': 'Icelandic', 'value': 'is'},
 {'label': 'Italian', 'value': 'it'},
 {'label': 'Japanese', 'value': 'ja'},
 {'label': 'Javanese', 'value': 'jv'},
 {'label': 'Georgian', 'value': 'ka'},
 {'label': 'Kazakh', 'value': 'kk'},
 {'label': 'Central Khmer', 'value': 'km'},
 {'label': 'Kannada', 'value': 'kn'},
 {'label': 'Korean', 'value': 'ko'},
 {'label': 'Kurdish', 'value': 'ku'},
 {'label': 'Kirghiz; Kyrgyz', 'value': 'ky'},
 {'label': 'Latin', 'value': 'la'},
 {'label': 'Luxembourgish; Letzeburgesch', 'value': 'lb'},
 {'label': 'Lao', 'value': 'lo'},
 {'label': 'Lithuanian', 'value': 'lt'},
 {'label': 'Latvian', 'value': 'lv'},
 {'label': 'Malagasy', 'value': 'mg'},
 {'label': 'Macedonian', 'value': 'mk'},
 {'label': 'Malayalam', 'value': 'ml'},
 {'label': 'Mongolian', 'value': 'mn'},
 {'label': 'Marathi', 'value': 'mr'},
 {'label': 'Malay', 'value': 'ms'},
 {'label': 'Maltese', 'value': 'mt'},
 {'label': 'Norwegian Bokmål', 'value': 'nb'},
 {'label': 'Nepali', 'value': 'ne'},
 {'label': 'Dutch; Flemish', 'value': 'nl'},
 {'label': 'Norwegian Nynorsk', 'value': 'nn'},
 {'label': 'Norwegian', 'value': 'no'},
 {'label': 'Occitan', 'value': 'oc'},
 {'label': 'Oriya', 'value': 'or'},
 {'label': 'Panjabi; Punjabi', 'value': 'pa'},
 {'label': 'Polish', 'value': 'pl'},
 {'label': 'Pushto; Pashto', 'value': 'ps'},
 {'label': 'Portuguese', 'value': 'pt'},
 {'label': 'Quechua', 'value': 'qu'},
 {'label': 'Romanian; Moldavian; Moldovan', 'value': 'ro'},
 {'label': 'Russian', 'value': 'ru'},
 {'label': 'Kinyarwanda', 'value': 'rw'},
 {'label': 'Northern Sami', 'value': 'se'},
 {'label': 'Sinhala; Sinhalese', 'value': 'si'},
 {'label': 'Slovak', 'value': 'sk'},
 {'label': 'Slovenian', 'value': 'sl'},
 {'label': 'Albanian', 'value': 'sq'},
 {'label': 'Serbian', 'value': 'sr'},
 {'label': 'Swedish', 'value': 'sv'},
 {'label': 'Swahili', 'value': 'sw'},
 {'label': 'Tamil', 'value': 'ta'},
 {'label': 'Telugu', 'value': 'te'},
 {'label': 'Thai', 'value': 'th'},
 {'label': 'Tagalog', 'value': 'tl'},
 {'label': 'Turkish', 'value': 'tr'},
 {'label': 'Uighur; Uyghur', 'value': 'ug'},
 {'label': 'Ukrainian', 'value': 'uk'},
 {'label': 'Urdu', 'value': 'ur'},
 {'label': 'Vietnamese', 'value': 'vi'},
 {'label': 'Volapük', 'value': 'vo'},
 {'label': 'Walloon', 'value': 'wa'},
 {'label': 'Xhosa', 'value': 'xh'},
 {'label': 'Chinese', 'value': 'zh'},
 {'label': 'Zulu', 'value': 'zu'}]